pager:
  diff: diffnav

prSections:
  - title: "Involved"
    filters: "sort:updated-desc is:open involves:@me -author:@me"
  - title: "My Pull Requests"
    filters: "is:open author:@me"
  - title: "Needs My Review"
    filters: "sort:updated-desc is:pr is:open review-requested:@me"

repoPaths:
  myprizepicks/*: ~/Developer/Source/*

keybindings:
  prs:
    - key: T
      command: gh enhance -R {{.RepoName}} {{.PrNumber}}
    - key: N
      command: >
        zsh -ic 'source ~/.config/zsh/functions/git.zsh && 
        pull-requests {{.RepoName}} {{.PrNumber}}'
    - key: P
      command: gh pr diff {{.PrNumber}} | claude --append-system-prompt "Review the following code changes for any potential bugs, repo standards and best practices."

