tap "homebrew/core"
tap "homebrew/bundle"
brew "awscli", link: false
brew "ctags"
brew "diff-so-fancy"
brew "fish"
brew "fzf"
brew "git"
brew "hub"
brew "neovim"
brew "nvm"
brew "stow"
brew "the_silver_searcher"
brew "thefuck"
brew "tmux"
brew "watchman"
