"$schema" = 'https://starship.rs/config-schema.json'

[line_break]
disabled = false

[python]
disabled = true

[aws]
disabled = true

[directory]
read_only = " "
read_only_style = "red"

[git_branch]
symbol = " "

[swift]
symbol = " "

[package]
symbol = "󰏗 "
