theme = "system"

[widgets]
displayed = [
    "default.spaces",
    "spacer",
    "default.time"
]

[widgets.default.spaces]
space.show-key = true
window.show-title = true
window.title.max-length = 50

[widgets.default.battery]
show-percentage = true
warning-level = 30
critical-level = 10

[widgets.default.time]
format = "J:mm:ss"
calendar.format = "J:mm"
calendar.show-events = true
calendar.allow-list = ["Appointments"]

[widgets.default.time.popup]
view-variant = "box"

[experimental.background]
displayed = false
height = "menu-bar"
blur = 3

[experimental.foreground]
height = "default"
horizontal-padding = 16
spacing = 16

