theme = "dark"

[widgets]
displayed = [
    "default.spaces",
]

[widgets.default.spaces]
space.show-key = true
window.show-title = true
window.title.max-length = 50

[experimental.background]
displayed = true
blur = 1

[experimental.foreground]
horizontal-padding = 16
spacing = 16

