-- vim.keymap.set('n', '<leader>gb', '<CMD>Gitsigns toggle_current_line_blame<CR>', { desc = 'Toggle blame' })
--
-- return {
--   {
--     'lewis6991/gitsigns.nvim',
--     enabled = false,
--     config = function()
--       require('gitsigns').setup {
--         signs = {
--           add = { text = '┃' },
--           change = { text = '┃' },
--           delete = { text = '_' },
--           topdelete = { text = '‾' },
--           changedelete = { text = '~' },
--           untracked = { text = '┆' },
--         },
--         on_attach = function(bufnr)
--           local gitsigns = require 'gitsigns'

--           local function map(mode, l, r, opts)
--             opts = opts or {}
--             opts.buffer = bufnr
--             vim.keymap.set(mode, l, r, opts)
--           end

--           map('n', '<leader>gD', gitsigns.diffthis, { desc = 'Diff' })

--           map('n', ']c', function()
--             if vim.wo.diff then
--               vim.cmd.normal { ']c', bang = true }
--             else
--               gitsigns.nav_hunk 'next'
--             end
--           end)

--           map('n', '[c', function()
--             if vim.wo.diff then
--               vim.cmd.normal { '[c', bang = true }
--             else
--               gitsigns.nav_hunk 'prev'
--             end
--           end)
--         end,
--       }
--     end,
--   },
-- }
