#!/usr/bin/env bash

TMP_SCROT="/tmp/lockscreen.png"

# take the screenshot, and pass it to ImageMagick
scrot $TMP_SCROT -e 'convert -scale 10% -scale 1000% -fill black -colorize 30% $f $f'

i3lock -c 222222 -i $TMP_SCROT