scheme: "Oxocarbon Light"
author: "shaunsingh/IBM"
base00: "ffffff"
base01: "f2f2f2"
base02: "d0d0d0"
base03: "161616"
base04: "37474F"
base05: "90A4AE"
base06: "525252"
base07: "08bdba"
base08: "ff7eb6"
base09: "ee5396"
base0A: "FF6F00"
base0B: "0f62fe"
base0C: "673AB7"
base0D: "42be65"
base0E: "be95ff"
base0F: "FFAB91"
