#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

source "$CONFIG_DIR/colors.sh"

sketchybar --bar position=top height=36 blur_radius=30 color=$BAR_COLOR

default=(
  padding_left=0
  padding_right=0
  icon.font="Hack Nerd Font:Regular:14.0"
  label.font="SF Pro:Semibold:12.0"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=10
  icon.padding_right=10
  label.padding_left=0
  label.padding_right=10
  background.padding_left=0
  background.padding_right=0
)
sketchybar --default "${default[@]}"

sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_focus_change

for sid in $(echo -e "1\n2\n3\n8\n9\n0"); do
  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change \
    --set space.$sid \
    background.color=$SECONDARY_ACCENT \
    background.corner_radius=5 \
    background.height=25 \
    background.drawing=on \
    background.padding_left=6 \
    background.padding_right=6 \
    y_offset=1 \
    icon="$sid" \
    icon.font="SF Pro:Bold:12.0" \
    icon.highlight_color=$WHITE \
    label.drawing=off \
    label.font="sketchybar-app-font:Regular:14.0" \
    label.y_offset=-1 \
    click_script="aerospace workspace $sid" \
    script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

sketchybar --add item chevron left \
  --set chevron icon= label.drawing=off

sketchybar --add item clock right \
  --set clock update_freq=10 script="$PLUGIN_DIR/clock.sh" \
  --add item battery right \
  --set battery update_freq=120 icon.drawing=on icon.font="Hack Nerd Font:Regular:14.0" script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change \
  --add item calendar_event right \
  --set calendar_event \
  update_freq=60 \
  script="$PLUGIN_DIR/calendar_event.sh" \
  click_script="open -a Calendar" \
  icon.font="Hack Nerd Font:Regular:12.0" \
  label.color="$WHITE" \
  background.drawing=on \
  background.color="$SECONDARY_ACCENT_TRANSPARENT" \
  background.corner_radius=8 \
  background.height=25

sketchybar --update
