#!/bin/bash

ICON_REDSHIFT=$(echo -e "<span foreground='#FFCC00'>\ue975</span>")
ICON_BLUELIGHT=$(echo -e "<span foreground='#5AC8FA'>\ue975</span>")
BRIGHTNESS_LEVEL=$(brightnessctl | grep -E -o '[0-9]{1,3}?%' | head -1)
REDSHIFT_STATUS=$(pidof redshift)

if [ $REDSHIFT_STATUS -gt 0 ]; then
  echo -e "${ICON_REDSHIFT} ${BRIGHTNESS_LEVEL}"
  echo -e "${ICON_REDSHIFT} ${BRIGHTNESS_LEVEL}"
else
  echo -e "${ICON_BLUELIGHT} ${BRIGHTNESS_LEVEL}"
  echo -e "${ICON_BLUELIGHT} ${BRIGHTNESS_LEVEL}"
fi