#!/bin/bash

ICON=$(echo -e '<span>\ue979</span>')
BRIGHTNESS_LEVEL=$(brightnessctl | grep -E -o '[0-9]{1,3}?%' | head -1)

echo -e "<span foreground='#FFE980'>${ICON}</span> ${BRIGHTNESS_LEVEL}"
echo -e "<span foreground='#FFE980'>${ICON}</span> ${BRIGHTNESS_LEVEL}"
# echo "${ICON} ${BRIGHTNESS_LEVEL}"