#!/bin/bash

COLOR_CHARGING="#4CD964"
COLOR_FULL="#4CD964"
COLOR_DISCHARGING="#FFFFFF"
COLOR_LOW="#FFCC00"
COLOR_LOWER="#FF9500"
COLOR_URGENT="#FF3B30"

ICON_CHARGING=$(echo -e "<span foreground='$COLOR_CHARGING'>\uebeb</span>")
ICON_FULL=$(echo -e "<span foreground='$COLOR_FULL'>\uebea</span>")
ICON_0=$(echo -e "<span foreground='$COLOR_URGENT'>\uebf2</span>")
ICON_10=$(echo -e "<span foreground='$COLOR_LOWER'>\uebf3</span>")
ICON_25=$(echo -e "<span foreground='$COLOR_LOW'>\uebf4</span>")
ICON_40=$(echo -e "<span>\uebf5</span>")
ICON_50=$(echo -e "<span>\uebf6</span>")
ICON_60=$(echo -e "<span>\uebf7</span>")
ICON_75=$(echo -e "<span>\uebf8</span>")
ICON_90=$(echo -e "<span>\uebf9</span>")
ICON_100=$(echo -e "<span>\uebfa</span>")

BATTERY=0
BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_LEVEL=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')

if [ "$BATTERY_STATE" = "Charging" ]; then
    echo "${ICON_CHARGING} ${BATTERY_LEVEL}%"
    echo "${ICON_CHARGING} ${BATTERY_LEVEL}%"
elif [[ $BATTERY_STATE = "Full" ]]; then
    echo "${ICON_FULL} ${BATTERY_LEVEL}%"
    echo "${ICON_FULL} ${BATTERY_LEVEL}%"
elif [[ $BATTERY_LEVEL -eq 100 ]]; then
    echo "${ICON_100} ${BATTERY_LEVEL}%"
    echo "${ICON_100} ${BATTERY_LEVEL}%"
elif [[ $BATTERY_LEVEL -ge 90 ]]; then
    echo "${ICON_90} ${BATTERY_LEVEL}%"
    echo "${ICON_90} ${BATTERY_LEVEL}%"
elif [[ $BATTERY_LEVEL -ge 75 ]]; then
    echo "${ICON_75} ${BATTERY_LEVEL}%"
    echo "${ICON_75} ${BATTERY_LEVEL}%"
elif [[ $BATTERY_LEVEL -ge 60 ]]; then
    echo "${ICON_60} ${BATTERY_LEVEL}%"
    echo "${ICON_60} ${BATTERY_LEVEL}%"
elif [[ $BATTERY_LEVEL -ge 50 ]]; then
    echo "${ICON_50} ${BATTERY_LEVEL}%"
    echo "${ICON_50} ${BATTERY_LEVEL}%"
elif [[ $BATTERY_LEVEL -ge 40 ]]; then
    echo "${ICON_40} ${BATTERY_LEVEL}%"
    echo "${ICON_40} ${BATTERY_LEVEL}%"
elif [[ $BATTERY_LEVEL -ge 25 ]]; then
    echo "${ICON_25} ${BATTERY_LEVEL}%"
    echo "${ICON_25} ${BATTERY_LEVEL}%"
elif [[ $BATTERY_LEVEL -ge 10 ]]; then
    echo "${ICON_10} ${BATTERY_LEVEL}%"
    echo "${ICON_10} ${BATTERY_LEVEL}%"
else
    echo "${ICON_0} ${BATTERY_LEVEL}%"
    echo "${ICON_0} ${BATTERY_LEVEL}%"
fi