#!/bin/bash

ICON=$(echo -e '<span font_desc="Typicons">\ue003</span>')
CONTAINER_COUNT=$(docker ps -q | wc -l | sed -r 's/^0$//g')

echo "${ICON} ${CONTAINER_COUNT:-0}"
echo "${ICON} ${CONTAINER_COUNT:-0}"