#!/bin/bash

PERCENT_USED=$(free | awk 'FNR == 2 {print int($3 * 100 / $2)}')

echo -e "<span foreground='#5AC8FA'>\ueca5</span> ${PERCENT_USED}%"
echo -e "<span foreground='#5AC8FA'>\ueca5</span> ${PERCENT_USED}%"
