#!/bin/bash

ICON=$(echo -e "<span>\uebe2</span>")
REDSHIFT_STATUS=$(pidof redshift)

if [ $REDSHIFT_STATUS -gt 0 ]; then
  echo "${ICON}"
  echo "${ICON}"
else
  echo "${ICON}"
  echo "${ICON}"
  echo "#999999"
fi
