#!/bin/bash

ICON=$(echo -e "<span>\ueae5</span>")
RESUME_DATE=$(cat /var/log/syslog | grep 'systemd-sleep' | grep 'resumed' | tail -1 | cut -d" " -f 3)
RESUME_TIME=$(date -d $RESUME_DATE +%s)
LOGIN_DATE=$(loginctl show-session 1 | grep 'Timestamp=' | cut -d" " -f 3)
LOGIN_TIME=$(date -d $LOGIN_DATE +%s)
CURRENT_TIME=$(date +%s)

if [[ $LOGIN_TIME -ge $RESUME_TIME ]]; then
  SECONDS=$(($CURRENT_TIME - $LOGIN_TIME))
else
  SECONDS=$(($CURRENT_TIME - $RESUME_TIME))
fi

HOURS=$(($SECONDS / 3600))
MINUTES=$(($SECONDS / 60))

if [[ $MINUTES -ge 60 ]]; then
  MINUTES=$(($MINUTES - 60))
fi

if [[ $HOURS -ge 1 ]]; then
  UPTIME=$(echo "${HOURS}h ${MINUTES:-0}m")
else
  UPTIME=$(echo "${MINUTES}m")
fi

echo "${ICON} ${UPTIME}"
echo "${ICON} ${UPTIME}"
