#!/bin/bash

ICON=$(echo -e "<span>\ueae5</span>")
RESUME_LOG=$(cat /var/log/syslog | grep 'systemd-sleep' | grep 'resumed' | tail -1 | cut -d" " -f 3)
CURRENT_TIME=$(date +%s)
RESUME_TIME=$(date -d $RESUME_LOG +%s)

SECONDS=$(($CURRENT_TIME - $RESUME_TIME))
HOURS=$(($SECONDS / 3600))
MINUTES=$((($SECONDS % 3600) / 60))

if [[ $HOURS -ge 1 ]]; then
  UPTIME=$(echo "${HOURS}h ${MINUTES}m")
else
  UPTIME=$(echo "${MINUTES}m")
fi

echo "${ICON} ${UPTIME}"
echo "${ICON} ${UPTIME}"
echo "#ffffff"