#!/bin/bash

ICON=$(echo -e "<span>\ueae5</span>")
RESUME_DATE=$(cat /var/log/syslog | grep 'systemd-sleep' | grep 'resumed' | tail -1 | cut -d" " -f 3)
RESUME_TIME=$(date -d $RESUME_DATE +%s)
LOGIN_DATE=$(loginctl session-status 1 | sed -n 2p | cut -d" " -f 7)
LOGIN_TIME=$(date -d $LOGIN_DATE +%s)
CURRENT_TIME=$(date +%s)

SECONDS=$(($CURRENT_TIME - $RESUME_TIME))
HOURS=$(($SECONDS / 3600))
MINUTES=$(($SECONDS / 60))

if [[ $MINUTES -ge 60 ]]; then
  MINUTES=$(($MINUTES - 60))
fi

if [[ $HOURS -ge 1 ]]; then
  UPTIME=$(echo "${HOURS}h ${MINUTES}m")
else
  UPTIME=$(echo "${MINUTES}m")
fi

if [[ $LOGIN_TIME -gt $RESUME_TIME ]]; then
  echo ""
  echo ""
else
  echo "${ICON} ${UPTIME}"
  echo "${ICON} ${UPTIME}"
fi
