#!/bin/bash

ICON_MUTE=$(echo -e "<span font_desc='Typicons'>\ue133</span>")
ICON_LOW=$(echo -e "<span font_desc='Typicons'>\ue135</span>")
ICON_MID=$(echo -e "<span font_desc='Typicons'>\ue132</span>")
ICON_HIGH=$(echo -e "<span font_desc='Typicons'>\ue134</span>")

VOLUME_LEVEL=$(amixer sget Master | grep -E -o "[0-9]{1,3}?%" | head -1 | tr -d "%")

if amixer sget Master | grep -q off; then
    echo "${ICON_MUTE} --"
    echo "${ICON_MUTE} --"
    echo "#999999"
elif [[ $VOLUME_LEVEL -ge 50 ]]; then
    echo "${ICON_HIGH} ${VOLUME_LEVEL}%"
    echo "${ICON_HIGH} ${VOLUME_LEVEL}%"
elif [[ $VOLUME_LEVEL -ge 20 ]]; then
    echo "${ICON_MID} ${VOLUME_LEVEL}%"
    echo "${ICON_MID} ${VOLUME_LEVEL}%"
else
    echo "${ICON_LOW} ${VOLUME_LEVEL}%"
    echo "${ICON_LOW} ${VOLUME_LEVEL}%"
fi