#!/bin/bash

QUALITY=$(grep wlp4s0 /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

RED="#FF3B30"
GREEN="#4CD964"
YELLOW="#FFCC00"

ICON_NO_CONNECTION=$(echo -e "<span foreground='$RED'>\ued67</span>")
ICON_100=$(echo -e "<span foreground='$GREEN'>\ued65</span>")
ICON_75=$(echo -e "<span>\ued65</span>")
ICON_50=$(echo -e "<span>\ued65</span>")
ICON_25=$(echo -e "<span foreground='$YELLOW'>\ued65</span>")

if [[ $QUALITY -ge 100 ]]; then
    echo "${ICON_100} ${QUALITY}%"
    echo "${ICON_100} ${QUALITY}%"
elif [[ $QUALITY -ge 75 ]]; then
    echo "${ICON_75} ${QUALITY}%"
    echo "${ICON_75} ${QUALITY}%"
elif [[ $QUALITY -ge 50 ]]; then
    echo "${ICON_50} ${QUALITY}%"
    echo "${ICON_50} ${QUALITY}%"
elif [[ $QUALITY -gt 0 ]]; then
    echo "${ICON_25} ${QUALITY}%"
    echo "${ICON_25} ${QUALITY}%"
else
    echo "${ICON_NO_CONNECTION} --"
    echo "${ICON_NO_CONNECTION} --"
    echo "#999999"
fi
